# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-13 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='product_image_link',
            new_name='item_image_link',
        ),
    ]
