# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-14 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20160613_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_total_investment',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
            preserve_default=False,
        ),
    ]
